version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root2025
        ports:
            - 27017:27017
        networks:
            - laravel
    app:
        build:
            context: ./docker/php
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
    web:
        image: nginx:latest
        container_name: laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
volumes:
    dbdata:

networks:
    laravel: