version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root2025
        ports:
            - 27017:27017
volumes:
    dbdata:


