version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:


